"""Add streak fields to User model

Revision ID: 8ec09f4e42df
Revises: 8ac630f67a20
Create Date: 2024-10-21 21:58:36.213822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec09f4e42df'
down_revision = '8ac630f67a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_login_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_balance_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_budget_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_balance_check', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_balance_check')
        batch_op.drop_column('last_login')
        batch_op.drop_column('monthly_budget_streak')
        batch_op.drop_column('monthly_balance_streak')
        batch_op.drop_column('daily_login_streak')

    # ### end Alembic commands ###
